default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ahoyanddevise_development

test:
  <<: *default
  database: ahoyanddevise_test

production:
  <<: *default
  database: ahoyanddevise_production
  username: ahoyanddevise
  password: <%= ENV['AHOYANDDEVISE_DATABASE_PASSWORD'] %>
