development: &default
  adapter: active_record
  active_record_adapter: postgresql
  database: ahoyanddevise_development
test:
  adapter: active_record
  active_record_adapter: default
  collecting: false
production:
  active_record_adapter: postgresql
  <% uri = URI.parse(ENV['DATABASE_URL']) %>
  host:     <%= uri.host %>
  username: <%= uri.username %>
  password: <%= uri.password %>
  port:     <%= uri.port %>
  database: <%= uri.path.sub('/', '') %>