development: &default
  adapter: active_record
  active_record_adapter: postgresql
  database: ahoyanddevise_development
test:
  adapter: active_record
  active_record_adapter: default
  collecting: false
production:
  <<: *default
  <% uri = URI.parse(ENV['DATABASE_URL']) %>
  database: <%= ENV['DATABASE_URL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  encoding: unicode
  pool:     5
